# diary/recurrence.py — RRULE expansion to generate session/occurrence datetimes.
#
# docs/03 §5: a diary.recurrence row holds an iCal RRULE string (e.g. a coach's weekly
# squad, a member's regular Tuesday slot). class_session rows / recurring bookings are
# generated by expanding that RRULE across a window.
#
# We prefer python-dateutil's rrulestr (it's already in requirements.txt) but keep a
# small dependency-free fallback for the common WEEKLY/DAILY case so this module imports
# and runs even where dateutil is absent (CI / py_compile / isolated self-verify).
#
# All datetimes are timezone-aware (tz from club.timezone, passed in by the caller).
# We never produce naive datetimes (docs/03 §10 timezone correctness).

import logging
from datetime import datetime, timedelta

log = logging.getLogger("diary.recurrence")

_WEEKDAY = {"MO": 0, "TU": 1, "WE": 2, "TH": 3, "FR": 4, "SA": 5, "SU": 6}


def expand(rrule, dtstart, *, window_start, window_end, until=None, max_count=500):
    """Expand an iCal RRULE into a list of occurrence-start datetimes within
    [window_start, window_end]. dtstart is the series anchor (tz-aware). `until` (date or
    datetime) caps the series. Returns a sorted list of tz-aware datetimes.

    Uses dateutil if available; otherwise a minimal FREQ=DAILY/WEEKLY[;BYDAY=..] fallback.
    """
    if dtstart is None:
        return []
    occ = _expand_dateutil(rrule, dtstart, window_end, until, max_count)
    if occ is None:
        occ = _expand_fallback(rrule, dtstart, window_end, until, max_count)
    return [d for d in occ if window_start <= d <= window_end]


def _expand_dateutil(rrule, dtstart, hard_end, until, max_count):
    try:
        from dateutil.rrule import rrulestr  # lazy; optional
    except Exception:
        return None
    try:
        s = rrule if rrule.upper().startswith(("RRULE:", "DTSTART")) else f"RRULE:{rrule}"
        rule = rrulestr(s, dtstart=dtstart)
        out = []
        for d in rule:
            if d > hard_end:
                break
            if until is not None and _as_dt(until, dtstart) is not None and d > _as_dt(until, dtstart):
                break
            out.append(d)
            if len(out) >= max_count:
                break
        return out
    except Exception:
        log.warning("dateutil rrule parse failed for %r — using fallback", rrule)
        return None


def _expand_fallback(rrule, dtstart, hard_end, until, max_count):
    """Minimal parser: FREQ=DAILY|WEEKLY ; INTERVAL=n ; BYDAY=MO,WE ; COUNT=n ; UNTIL=...
    Enough for the seed's weekly squads / daily court rules; complex RRULEs need dateutil."""
    parts = {}
    for tok in rrule.replace("RRULE:", "").split(";"):
        if "=" in tok:
            k, v = tok.split("=", 1)
            parts[k.strip().upper()] = v.strip()

    freq = parts.get("FREQ", "WEEKLY").upper()
    interval = int(parts.get("INTERVAL", "1") or "1")
    count = int(parts["COUNT"]) if "COUNT" in parts else None
    bydays = [_WEEKDAY[d] for d in parts["BYDAY"].split(",")] if "BYDAY" in parts else None
    end = _as_dt(until, dtstart) or hard_end
    if "UNTIL" in parts:
        u = _parse_until(parts["UNTIL"], dtstart)
        if u:
            end = min(end, u)

    out = []
    if freq == "DAILY":
        step = timedelta(days=interval)
        cur = dtstart
        while cur <= end and len(out) < max_count:
            out.append(cur)
            if count and len(out) >= count:
                break
            cur += step
    elif freq == "WEEKLY":
        days = bydays if bydays is not None else [dtstart.weekday()]
        week0 = dtstart - timedelta(days=dtstart.weekday())
        w = 0
        while len(out) < max_count:
            base = week0 + timedelta(weeks=w * interval)
            if base - timedelta(days=7) > end:
                break
            for wd in sorted(days):
                occ = base.replace(hour=dtstart.hour, minute=dtstart.minute,
                                   second=0, microsecond=0) + timedelta(days=wd)
                if occ < dtstart or occ > end:
                    continue
                out.append(occ)
                if count and len(out) >= count:
                    return sorted(out)[:max_count]
            w += 1
    else:
        log.warning("recurrence fallback: unsupported FREQ=%s — single occurrence only", freq)
        out = [dtstart] if dtstart <= end else []
    return sorted(out)[:max_count]


def _as_dt(value, ref):
    """Coerce a date/datetime `until` to a tz-aware datetime aligned to ref's tzinfo."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=ref.tzinfo)
    # a date -> end of that day in ref's tz
    return datetime(value.year, value.month, value.day, 23, 59, 59, tzinfo=ref.tzinfo)


def _parse_until(s, ref):
    for fmt in ("%Y%m%dT%H%M%SZ", "%Y%m%dT%H%M%S", "%Y%m%d"):
        try:
            d = datetime.strptime(s, fmt)
            return d if d.tzinfo else d.replace(tzinfo=ref.tzinfo)
        except ValueError:
            continue
    return None
