// invoice.js — render a printable COACHING invoice for ?client=<id>&month=<YYYY-MM>.
// Fetches GET /api/coach/clients/<id>/invoice?month= via TFAuth (coach-auth), renders, offers Print.
// Self-contained (no api.js) so it stays lean, mirroring receipt.js.
(function () {
  function qp(n) { return new URLSearchParams(location.search).get(n) || ""; }
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }
  function money(minor, ccy) {
    var sym = (ccy === "ZAR" || !ccy) ? "R" : (ccy + " ");
    return sym + ((Number(minor || 0)) / 100).toFixed(2);
  }
  function fmtDate(iso) {
    if (!iso) return "";
    var d = new Date(iso);
    return isNaN(d) ? String(iso).slice(0, 16).replace("T", " ")
      : d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
  }
  function monthLabel(ym) {
    if (!ym) return "";
    var p = String(ym).split("-");
    try { return new Date(p[0], (parseInt(p[1], 10) || 1) - 1, 1)
      .toLocaleDateString(undefined, { month: "long", year: "numeric" }); } catch (e) { return ym; }
  }
  var CHIP = { paid: "paid", owed: "owed", written_off: "woff" };
  var LABEL = { paid: "paid", owed: "owed", written_off: "written off" };

  function render(inv) {
    var t = inv.totals || {};
    var rows = (inv.lines || []).map(function (l) {
      return '<tr><td>' + esc(fmtDate(l.at)) + '</td><td>' + esc(l.description || "Lesson") +
        (l.note ? ' <span style="color:#999">— ' + esc(l.note) + '</span>' : '') +
        '</td><td class="i-c"><span class="i-chip ' + (CHIP[l.status] || "") + '">' +
        (LABEL[l.status] || esc(l.status)) + '</span></td>' +
        '<td class="num">' + money(l.gross_minor, inv.currency) + '</td></tr>';
    }).join("") || '<tr><td colspan="4" style="color:#999">No coaching activity this month.</td></tr>';

    document.getElementById("i-body").innerHTML =
      '<div class="i-head">' +
        '<div><div class="i-club">' + esc(inv.club_name) + '</div>' +
          '<div style="color:#888;font-size:.85rem;margin-top:2px">Coaching statement</div></div>' +
        '<div class="i-meta"><b>' + esc(monthLabel(inv.month)) + '</b><br>' +
          'Coach: ' + esc(inv.coach_name || "—") + '</div>' +
      '</div>' +
      '<h1>Statement</h1>' +
      '<p style="margin:0 0 14px;color:#555">For <b>' + esc(inv.client_name || "—") + '</b>' +
        (inv.client_email ? ' · ' + esc(inv.client_email) : '') + '</p>' +
      '<table><thead><tr><th>Date</th><th>Item</th><th></th><th class="num">Amount</th></tr></thead>' +
        '<tbody>' + rows + '</tbody></table>' +
      (t.paid_minor ? tot("Paid this month", money(t.paid_minor, inv.currency), "") : "") +
      (t.written_off_minor ? tot("Written off", "−" + money(t.written_off_minor, inv.currency), "i-mute") : "") +
      '<div class="i-total"><span>Amount due</span><span>' + money(t.owed_minor, inv.currency) + '</span></div>' +
      (t.owed_minor
        ? '<p class="i-pay">Settle online any time — pay this and anything else you owe in one payment at ' +
          '<b>your account page</b>, and your balance clears to zero.</p>'
        : '<p class="i-pay">Nothing outstanding — thank you!</p>') +
      '<div class="i-actions">' +
        '<button class="i-btn" onclick="window.print()">Print / Save PDF</button>' +
        '<a class="i-btn ghost" href="/coach.html">Back to console</a>' +
      '</div>';
    document.getElementById("i-foot").textContent = "Generated by " + (inv.club_name || "the club") + ".";
  }
  function tot(label, val, cls) {
    return '<div class="i-total i-sub ' + (cls || "") + '"><span>' + esc(label) + '</span><span>' + val + '</span></div>';
  }

  window.Invoice = {
    start: async function () {
      var client = qp("client"), month = qp("month");
      var auth = window.TFAuth;
      if (auth && auth.ready) { try { await auth.ready(); } catch (e) {} }
      if (!client || !auth || !auth.apiJSON) {
        document.getElementById("i-body").innerHTML =
          '<p style="color:#b4232a">Couldn\'t load this statement.</p>' +
          '<div class="i-actions"><a class="i-btn ghost" href="/coach.html">Back to console</a></div>';
        return;
      }
      try {
        var res = await auth.apiJSON("/api/coach/clients/" + encodeURIComponent(client) +
          "/invoice" + (month ? ("?month=" + encodeURIComponent(month)) : ""));
        render(res.invoice || res);
      } catch (e) {
        var msg = (e && (e.message || (e.body && e.body.error))) || "Statement unavailable.";
        document.getElementById("i-body").innerHTML =
          '<p style="color:#b4232a">' + esc(msg) + '</p>' +
          '<div class="i-actions"><a class="i-btn ghost" href="/coach.html">Back to console</a></div>';
      }
    },
  };
})();
